alias bim='vim'
alias be='bundle exec'
alias r='bundle exec rails'
alias rc='bundle exec rails console'
alias ne='nvm exec --silent'
alias yr='yarn run --silent'
alias neyr='nvm exec --silent yarn run --silent'
